---
title: "Exploratory Data Analysis"
---

- [Restaurant EDA](RestaurantEDA/RestaurantEDA.html)
- [Survival plot model and sparklyr](survival_plot_sparklyr/survival_plot_sparklyr.html)
- [Shiny - ggplot - spark - ml_linear_regression - iris ](shiny_ggplot_spark_transformation/shiny_ggplot_spark_transformation.html)
- [Connect multiple local spark nodes](sc_multiple_nodes/sc_multiple_nodes.html)
- [How to convert dplyr code to sql code](dplyr_to_sql/dplyr_to_sql.html)
- [Connect multiple spark nodes](sc_multiple_nodes/sc_multiple_nodes.html)
- [Instacart Market Basket Analysis](instacart_market_basket_analysis/instacart_market_basket.html)
- [White Bllod Cells Classification](White_blood_Cells/dataset-master/White_blood_cell.html)
- [Santander Customer Transaction Prediction](santander_customer_transaction_prediction/santandar_costumer_trans_pred.html)
_ [Streaming - detect new csv file - Dashboard with Shiny](Dashboard/Dashboard.html)
- [Santander customer transaction prediction with rpart](santander_customer_transaction_prediction/santander_costumer_trans_pred.html)
- [Santander customer transaction prediction with keras (MLP)](santander_customer_transaction_prediction/santandar_costumer_trans_pred_keras.html)
- [Santander customer transaction prediction with xgboost](santander_customer_transaction_prediction/santander_trans_pred_xgboost.html)
- [Santander customer transaction prediction with xgb.cv & xgb.train](santander_customer_transaction_prediction/Santander_trans_pred_xgboost_cleanup.html)
- [Facial & Smile recognisation](Smile_kinships/parental_facial_recogn.html)
- [Smile Kinships detection](Smile_kinships/Smile_related_keras.html)
- [Face Recognition using face_recognition library](FC_images_known_faces/images_known_faces.html)
- [Generate dataset from webcam - train model using openCV and detect faces](FC_dataset_generator_trained_model/dataset_generator_trained_model.html)
- [Generate and save dataset to sqlite db, train model using openCV,  detect and reconize faces from webcam](FC_name_Id_generator_image_sqlite_train_model/name_Id_dataset_generator_sqlite_train_model.html)
- [Face recognition by comapring distance (weigth) between image arrays](FC_weights_image_compare_speak/compare_images_speak.html)
- [Face recognition eyes blink destector](FC_eye_blink_detection/eye_blink_detector.html)
- [IEEE-CIS Fraud Detection](Fraud_detection/IEEE-CIS/IEEE-CIS.html)
- [Predict Future Monthly Sales](predict-future-sales/predict_future_sales.html)
- [Predict the number of attempts by xgboost](bowl-2019/bowl_19_xgb.html)
- [Dealing with unbalanced multiclasses with caret](unbalanced_multi_class/unbalanced_multiclass.html)