---
title: "How to tune hyperparameters with Python and scikit-learn"
author: "Karim Mezhoud"
date: '`r Sys.Date()`'
output:
  html_document:
    number_sections: true
    fig_caption: true
    toc: true
    fig_width: 7
    fig_height: 6
    theme: cosmo
    highlight: tango
    code_folding: show #hide
    self_contained: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, error=TRUE, warning =TRUE)
knitr::opts_chunk$set(fig.width=12, fig.height=8) 
```

## set python version and anaconda environment
```{r}
#reticulate::use_python("/Users/Mezhoud/miniconda3/envs/Ana_Env/bin/python", required = TRUE)
#reticulate::use_python("/Users/Mezhoud/miniconda3/bin/python", required = TRUE)
reticulate::use_python("/Users/Mezhoud/venv/bin/python3", required = TRUE)
reticulate::py_config()
```


```{r}
reticulate::py_module_available("keras")
```

## load packages

```{r}
library(reticulate)
```


```{python}
# import the necessary packages
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from imutils import paths
import numpy as np
import argparse
import imutils
import time
import cv2
import os

```

