---
title: "ImageNet: VGGNet, ResNet, Inception, and Xception with Keras"
author: "Karim Mezhoud"
date: '`r Sys.Date()`'
output:
  html_document:
    number_sections: true
    fig_caption: true
    toc: true
    fig_width: 7
    fig_height: 6
    theme: cosmo
    highlight: tango
    code_folding: show #hide
    self_contained: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, error=TRUE, warning =TRUE)
knitr::opts_chunk$set(fig.width=12, fig.height=8) 
```

## set python version and anaconda environment
```{r}
reticulate::use_python("/Users/Mezhoud/miniconda3/envs/Ana_Env/bin/python", required = TRUE)
#reticulate::use_python("/Users/Mezhoud/miniconda3/bin/python", required = TRUE)
reticulate::use_condaenv("miniconda3")
reticulate::py_config()
```

```{r}
reticulate::py_module_available("sklearn")
reticulate::conda_list()
```

## load packages

```{r}
library(reticulate)
```

```{python}
# import the necessary packages
from keras.applications import ResNet50
from keras.applications import InceptionV3
from keras.applications import Xception # TensorFlow ONLY
from keras.applications import VGG16
from keras.applications import VGG19
from keras.applications import imagenet_utils
from keras.applications.inception_v3 import preprocess_input
from keras.preprocessing.image import img_to_array
from keras.preprocessing.image import load_img
import numpy as np
import argparse
import cv2

```


