---
title: "Fancifing Excel Table"
author: "Karim Mezhoud"
date: '`r Sys.Date()`'
output:
  html_document:
    number_sections: true
    fig_caption: true
    toc: true
    fig_width: 7
    fig_height: 6
    theme: cosmo
    highlight: tango
    code_folding: show #hide
    self_contained: no
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, error=FALSE)
knitr::opts_chunk$set(fig.width=12, fig.height=8) 
```

## Load packages
```{r}
library(dplyr)
library(readxl)
library(kableExtra)
library(stringr)

options(knitr.table.format = "html", knitr.kable.NA = '') 
```

```{r}
rawdat <- read_excel("schedule_615.xlsx")
cdat   <- rawdat %>%  filter(Date > "2018-04-01")
```


```{r}
# parse topics - same code for all three vars. Yes I could have applied a function. 
topiclist <- which(!is.na(cdat$Topics))
cdat$Topics[topiclist] <- paste0("<ul><li>", cdat$Topics[topiclist], "</li></ul>")
cdat$Topics[topiclist] <- str_replace(cdat$Topics[topiclist], "\\*", '</li><li>')
```


```{r}
knitr::kable(cdat, align="l", escape=FALSE, table.attr = "style=\"color: black;\"") %>% 
  kable_styling(bootstrap_options = c("hover", "striped", "responsive")) %>% 
  column_spec(1, width="1%") %>% column_spec(2, width="1%") %>%
  column_spec(3, width="20%") %>% column_spec(4, width="30%") %>%
  column_spec(5, width="30%")

```

